### ISSUE TITLE
Default Image for Posts / Pages

### ISSUE THREAD

**Issue by masteradhoc** [janw-me/default-featured-image#1]
Hey @janw-me
Thanks for the great small and efficient plugin! Would be amazing if we can add a small setting here: /wp-admin/options-media.php
I would only need a featured image for posts (or in my case CPT) f.e. not for posts and pages. :)

Thanks
Brian

**Comment by janw-me** [comment]
Hi @masteradhoc 

It is possible to only set different images per post type, or disable post types.
I have multiple examples in the [FAQ](https://wordpress.org/plugins/default-featured-image/#can%20i%20set%20a%20different%20image%20for%20a%20custom%20post%20type%3F)

For your specific use case it would be.

```php
add_filter( 'dfi_thumbnail_id', 'dfi_posttype_book', 10, 2 );
function dfi_posttype_book( $dfi_id, $post_id ) {
    $post = get_post( $post_id );
    if ( 'book' === $post->post_type ) {
        return $dfi_id; // the original featured image id.
    }

    return 0; // no DFI  for other post types.
}
```

I'm guessing you don't need help where to put this right ;)

Why isn't this a setting? I didn't want to complicate the UI, and it can open a can of worms of the order to pick.
Especially when adding taxonomy support.
And for the 10 years of this plugins existence these snippets have worked well.

Let me know how it goes.

**Comment by masteradhoc** [comment]
@janw-me Totally overlooked. Thank you very much!
